class _Config(object):
    APPINSIGHTS_INSTRUMENTATIONKEY = None
    TITAN_ACQUIRE_TIMEOUT_SECONDS = None
    TITAN_AD_CLIENT_ID = None
    TITAN_AD_TENANT_ID = None
    TITAN_AZURE_BLOB_ACCOUNT_NAME = None
    TITAN_AZURE_BLOB_CONTAINER_NAME = None
    TITAN_AZURE_BLOB_ENDPOINT = None
    TITAN_AZURE_BLOB_SAS_TOKEN = None
    TITAN_AZURE_CONTAINER_CPU_COUNT = 1
    TITAN_AZURE_CONTAINER_IMAGE_NAME = None
    TITAN_AZURE_CONTAINER_LOCATION = None
    TITAN_AZURE_CONTAINER_NAME = None
    TITAN_AZURE_CONTAINER_OS_TYPE = 'Linux'
    TITAN_AZURE_CONTAINER_RAM_GB = 2
    TITAN_AZURE_CONTAINER_RSG_NAME = None
    TITAN_EXTRACT_TIMEOUT_SECONDS = None
    DEBUG = None
    SQLALCHEMY_DATABASE_URI = None
    SQLALCHEMY_TRACK_MODIFICATIONS = None

class DevelopmentConfig(_Config):
    TITAN_ACQUIRE_TIMEOUT = 600
    TITAN_EXTRACT_TIMEOUT = 600
    DEBUG = True
    SQLALCHEMY_TRACK_MODIFICATIONS = True


class TestConfig(_Config):
    TITAN_ACQUIRE_TIMEOUT = 600
    TITAN_EXTRACT_TIMEOUT = 600
    DEBUG = False
    SQLALCHEMY_TRACK_MODIFICATIONS = True


class ProductionConfig(_Config):
    TITAN_ACQUIRE_TIMEOUT = 3600
    TITAN_EXTRACT_TIMEOUT = 3600
    DEBUG = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False


CONFIGURATIONS = {
    None: _Config,
    "dev": DevelopmentConfig,
    "test": TestConfig,
    "prod": ProductionConfig
}
